#!/bin/sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
KIT_DIR="$(CDPATH= cd -- "${SCRIPT_DIR}/.." && pwd)"
NETWORK="${KIT_DIR}/files/etc/config/network"
SMARTAP="${KIT_DIR}/files/etc/config/smartap"
BOOTSTRAP="${KIT_DIR}/files/usr/sbin/smartap-bootstrap"
SECURITY="${KIT_DIR}/files/usr/sbin/cr6608-security-apply"
DASHCTL="${KIT_DIR}/files/www/cgi-bin/dashctl"
SELFTEST="${KIT_DIR}/files/usr/sbin/smartap-selftest"
PORT_READINESS="${KIT_DIR}/files/usr/sbin/cr6608-port-readiness"
PORT_READINESS_LIB="${KIT_DIR}/files/usr/libexec/cr6608-port-readiness-lib"

[ -f "${PORT_READINESS}" ]
[ -f "${PORT_READINESS_LIB}" ]
grep -Fq 'scope=read-only-no-phy-cycle-no-generated-traffic' "${PORT_READINESS}"
grep -Fq -- '--require-carrier' "${PORT_READINESS}"
grep -Fq -- '--require-traffic' "${PORT_READINESS}"
grep -Fq 'cr6608_bridge_membership_valid' "${PORT_READINESS_LIB}"
grep -Fq 'cr6608_vlan_contract_valid' "${PORT_READINESS_LIB}"
grep -Fq 'cr6608_wan_contract' "${PORT_READINESS_LIB}"
grep -Fq '[ "$device" = wan ]' "${PORT_READINESS_LIB}"

for port in lan1 lan2 lan3; do
  grep -Fq "list ports '${port}'" "${NETWORK}"
  grep -Fq "config port '${port}'" "${SMARTAP}"
done
grep -Fq "option stp '0'" "${NETWORK}"
grep -Fq "option packet_steering '0'" "${NETWORK}"
! grep -Fq "option forward_delay '2'" "${NETWORK}"
grep -Fq "option loop_guard '0'" "${SMARTAP}"
grep -Fq "option loop_guard_owner 'inherit'" "${SMARTAP}"
grep -Fq 'seedv smartap.security.loop_guard 0 smartap' "${BOOTSTRAP}"
grep -Fq 'seedv smartap.security.loop_guard_owner inherit smartap' "${BOOTSTRAP}"
grep -Fq 'loop="${loop:-0}"' "${SECURITY}"
grep -Fq 'owner="${owner:-inherit}"' "${SECURITY}"
grep -Fq '[ "$owner" = smartap ] || return 0' "${SECURITY}"
grep -Fq 'uci set "$bridge.forward_delay=2"' "${SECURITY}"
grep -Fq 'uci -q delete "$bridge.forward_delay"' "${SECURITY}"
grep -Fq 'loop="${loop:-0}"' "${DASHCTL}"
grep -Fq 'physical WAN port is reserved' "${NETWORK}"
grep -Fq 'for IF in lan1 lan2 lan3 wan' "${SELFTEST}"
grep -Fq 'for counter in rx_errors tx_errors' "${SELFTEST}"
! grep -Fq 'for counter in rx_errors tx_errors rx_crc_errors' "${SELFTEST}"
grep -Fq '"port_errors":%s' "${SELFTEST}"
grep -Fq '"port_drops":%s' "${SELFTEST}"
grep -Fq '"port_errors_total":%s' "${SELFTEST}"
grep -Fq '"tx_timeouts":%s' "${SELFTEST}"
grep -Fq '"tx_timeouts_total":%s' "${SELFTEST}"
grep -Fq '/sys/class/net/eth[01]/queues/tx-*/tx_timeout' "${SELFTEST}"
grep -Fq 'tx_timeouts=$((tx_timeouts_total - prev_timeouts))' "${SELFTEST}"
grep -Fq '[ "$tx_timeouts" -ge 1 ]' "${SELFTEST}"
grep -Fq 'port_errors=$((port_errors_total - prev_errors))' "${SELFTEST}"
grep -Fq '[ "$prev_epoch" -gt 0 ]' "${SELFTEST}"
grep -Fq 'pidof "$process"' "${SELFTEST}"
grep -Fq 'for process in netifd uhttpd rpcd' "${SELFTEST}"
grep -Fq 'run_limit 3 /bin/ubus -t 2 list session' "${SELFTEST}"
grep -Fq 'ubus-session' "${SELFTEST}"
grep -Fq 'pidof dropbear' "${SELFTEST}"
grep -Fq 'pidof hostapd' "${SELFTEST}"
! grep -Fq 'pgrep -x' "${SELFTEST}"
grep -Fq 'hostapd_expected=0' "${SELFTEST}"
grep -Fq 'if ! wifi_schedule_off_now; then' "${SELFTEST}"
grep -Fq 'if wifi_schedule_off_now; then' "${KIT_DIR}/files/usr/sbin/cr6608-wifi-sentinel"

printf 'dsa_port_contract=pass\n'
