#!/bin/sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
JS="$ROOT/files/www/dashboard.js"
HTML="$ROOT/files/www/index.html"
CSS="$ROOT/files/www/dashboard.css"
LUCI="$ROOT/files/etc/config/luci"
RESOURCES="$ROOT/files/www/luci-static/resources"
MENU_ARGON="$RESOURCES/menu-argon.js"
MENU_ARGON_RUNTIME="$ROOT/tests/test-menu-argon-runtime.js"
UHTTPD="$ROOT/files/etc/config/uhttpd"
LUCI_SYSAUTH="$ROOT/files/usr/share/ucode/luci/template/themes/argon/sysauth.ut"
LUCI_VERSION="$ROOT/files/usr/share/ucode/luci/version.uc"
ARGON_CSS="$ROOT/files/www/luci-static/argon/css/cascade.css"
ARGON_MOBILE_CSS="$ROOT/files/www/luci-static/argon/css/cr6608-mobile.css"
ARGON_LOCALTIME_JS="$ROOT/files/www/luci-static/argon/js/cr6608-localtime.js"
ARGON_HEADER="$ROOT/files/usr/share/ucode/luci/template/themes/argon/header.ut"
UHTTPD_SECURITY_HEADERS="$ROOT/files/etc/uhttpd/security-headers.json"
SMARTAP_ONLY_MIGRATION="$ROOT/files/etc/uci-defaults/99-cr6608-smartap-only"
BUILD="$ROOT/build.sh"
PUBLISH="$ROOT/publish-validated-image.sh"
INSPECTOR="$ROOT/inspect-image.sh"
LOGIN_CACHE_CONTRACT="$ROOT/tests/test-login-cache-contract.sh"
LOGIN_RUNTIME="$ROOT/tests/test-login-runtime.js"
EXPECTED_DASHBOARD_UI_VERSION='cr6608-smartap-v86-live-design-27.0.0'
EXPECTED_DASHBOARD_CSS_ASSET='/dashboard.css?v=20260902-smartap-v86-live-design-v1'
EXPECTED_DASHBOARD_JS_ASSET='/dashboard.js?v=20260902-smartap-v86-live-design-v1'

grep -Fq "var UI_VERSION = \"$EXPECTED_DASHBOARD_UI_VERSION\";" "$JS"
[ "$(grep -Fxc "  <meta name=\"smartap-ui-version\" content=\"$EXPECTED_DASHBOARD_UI_VERSION\">" "$HTML")" -eq 1 ]
grep -Fq '<meta name="smartap-stable-dom" content="pass">' "$HTML"
grep -Fq '<meta name="smartap-design-system" content="unified">' "$HTML"
[ -s "$CSS" ]
[ "$(grep -Fc "$EXPECTED_DASHBOARD_CSS_ASSET" "$HTML")" -eq 1 ]
[ "$(grep -Fxc "  <link rel=\"stylesheet\" href=\"$EXPECTED_DASHBOARD_CSS_ASSET\">" "$HTML")" -eq 1 ]
[ "$(grep -Fc "$EXPECTED_DASHBOARD_JS_ASSET" "$HTML")" -eq 1 ]
[ "$(grep -Fxc "  <script src=\"$EXPECTED_DASHBOARD_JS_ASSET\" defer></script>" "$HTML")" -eq 1 ]
grep -Fqx "EXPECTED_DASHBOARD_UI_VERSION=\"$EXPECTED_DASHBOARD_UI_VERSION\"" "$INSPECTOR"
grep -Fqx "EXPECTED_DASHBOARD_CSS_ASSET=\"$EXPECTED_DASHBOARD_CSS_ASSET\"" "$INSPECTOR"
grep -Fqx "EXPECTED_DASHBOARD_JS_ASSET=\"$EXPECTED_DASHBOARD_JS_ASSET\"" "$INSPECTOR"
grep -Fqx "EXPECTED_DASHBOARD_UI_VERSION='$EXPECTED_DASHBOARD_UI_VERSION'" "$LOGIN_CACHE_CONTRACT"
grep -Fqx "EXPECTED_DASHBOARD_CSS_ASSET='$EXPECTED_DASHBOARD_CSS_ASSET'" "$LOGIN_CACHE_CONTRACT"
grep -Fqx "EXPECTED_DASHBOARD_JS_ASSET='$EXPECTED_DASHBOARD_JS_ASSET'" "$LOGIN_CACHE_CONTRACT"
grep -Fq ': extension === ".css" ? "text/css; charset=utf-8"' "$LOGIN_RUNTIME"
[ "$(grep -Fc '/dashboard.css?v=' "$INSPECTOR")" -eq 1 ]
[ "$(grep -Fc '/dashboard.js?v=' "$INSPECTOR")" -eq 1 ]
! grep -Fq '<style' "$HTML"
if grep -Eq '\.innerHTML[[:space:]]*=|\.outerHTML[[:space:]]*=|replaceChildren[[:space:]]*\(' "$JS"; then
  echo 'forbidden structural HTML assignment remains' >&2
  exit 1
fi
! grep -Fq 'loginPassToggle' "$HTML"
! grep -Fq 'setPasswordVisible' "$JS"
grep -Fq 'function normalizeMobilePassword(value)' "$JS"
grep -Fq 'url(/luci-static/resources/icons/loading.svg)' "$ARGON_CSS"
! grep -Fq 'url(/luci-static/resources/icons/loading.gif)' "$ARGON_CSS"
grep -Fq '/css/cr6608-mobile.css?v=20260816-argon-mobile-v64-rtlfix1' "$ARGON_HEADER"
grep -Fq '/js/cr6608-localtime.js?v=20260816-argon-localtime-v64-rtlfix1' "$ARGON_HEADER"
grep -Fq "http.header('Content-Security-Policy', \"default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; font-src 'self' data:; frame-ancestors 'self'; object-src 'none'; base-uri 'self'; form-action 'self'\");" "$ARGON_HEADER"
[ "$(grep -Fc "'unsafe-eval'" "$ARGON_HEADER")" -eq 1 ]
grep -Fq "\"Content-Security-Policy\", \"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; font-src 'self'; frame-ancestors 'self'; object-src 'none'; base-uri 'self'; form-action 'self'\"" "$UHTTPD_SECURITY_HEADERS"
! grep -Fq "\"Content-Security-Policy\", \"default-src 'self'; script-src 'self' 'unsafe-inline'" "$UHTTPD_SECURITY_HEADERS"
! grep -Fq "'unsafe-eval'" "$UHTTPD_SECURITY_HEADERS"
! grep -Fq "'unsafe-eval'" "$HTML"
grep -Fq 'class="cr6608-menu-lines" aria-hidden="true"><i></i><i></i><i></i></span>' "$ARGON_HEADER"
grep -Fq 'body.logged-in .showSide::before' "$ARGON_MOBILE_CSS"
grep -Fq 'content: none !important' "$ARGON_MOBILE_CSS"
grep -Fq '.showSide > .cr6608-menu-lines > i' "$ARGON_MOBILE_CSS"
grep -Fq 'body.logged-in #maincontent .tabs' "$ARGON_MOBILE_CSS"
grep -Fq 'body.logged-in #maincontent .cbi-tabmenu' "$ARGON_MOBILE_CSS"
grep -Fq 'body[data-page="admin-status-overview"]' "$ARGON_MOBILE_CSS"
grep -Fq 'unicode-bidi: isolate' "$ARGON_MOBILE_CSS"
grep -Fq 'function isolateTokens(value)' "$ARGON_LOCALTIME_JS"
grep -Fq 'window.setInterval(sync, 500)' "$ARGON_LOCALTIME_JS"
grep -Fq 'body[data-page="admin-network-wireless"]' "$ARGON_MOBILE_CSS"
grep -Fq '.td[data-name="_badge"]' "$ARGON_MOBILE_CSS"
grep -Fq '.td[data-name="_stat"]' "$ARGON_MOBILE_CSS"
grep -Fq "var h=d.services" "$JS"
! grep -Fq "var h=d.health;if(!h||typeof h!=='object')" "$JS"
grep -Fq 'service_processes="$(for service_comm in /proc/[0-9]*/comm; do' "$ROOT/files/www/cgi-bin/dashapi2"
grep -Fq '"services":%s' "$ROOT/files/www/cgi-bin/dashapi2"
grep -Fq 'method: "POST", credentials: "same-origin", cache: "no-store"' "$JS"
grep -Fq 'fetchWithTimeout(authUrl(API + "?lite=1&probe=1&live=1"), { credentials:"same-origin", cache:"no-store"' "$JS"
! grep -Fq 'fetchWithTimeout(authUrl(API), { credentials:"same-origin", cache:"no-store"' "$JS"
grep -Fq 'fetchWithTimeout(authUrl(full ? API + "?live=1" : API + "?lite=1&live=1"), { credentials:"same-origin"' "$JS"
grep -Fq 'var fetchOptions = { credentials:"same-origin", cache:"no-store"' "$JS"
grep -Fq 'insightCategory:' "$JS"
grep -Fq 'data-insight-category' "$JS"
grep -Fq 'role="tablist" aria-label=' "$JS"
grep -Fq 'aria-controls="insight-panel" tabindex=' "$JS"
grep -Fq 'id="insight-panel" role="tabpanel" aria-labelledby=' "$JS"
grep -Fq 'bindTabKeyboard(button, "[data-insight-category]", activateInsightTab)' "$JS"
grep -Fq 'cats[selected].forEach(function (f)' "$JS"
grep -Fq 'else if (id === "insights"' "$JS"
grep -Fq '!data.lite || !$("insights").innerHTML' "$JS"
grep -Fq '["insights","insights","signal"]' "$JS"
! grep -Fq 'smartap.cardOrder' "$JS"
! grep -Fq 'draggable="true"' "$JS"
grep -Fq 'wifi_radio0' "$JS"
grep -Fq 'wifi_radio1' "$JS"
! grep -Fq 'wifi_toggle' "$JS"
grep -Fq 'w.up === true' "$JS"
grep -Fq 'x.requested_dbm != null ? x.requested_dbm : txp.requested_dbm' "$JS"
grep -Fq 'x.applied_dbm != null ? x.applied_dbm : txp.applied_dbm' "$JS"
grep -Fq 'x.max_dbm != null ? x.max_dbm : txp.max_dbm' "$JS"
grep -Fq 'var bootstrapLite = !state.latest && !requestedFull' "$JS"
grep -Fq 'if (forceFull === true) state.fullRefreshRequested = true' "$JS"
grep -Fq 'var retryDelay = requestedFull && !superseded' "$JS"
grep -Fq 'Math.min(3000, Math.max(1, state.apiFails) * 750)' "$JS"
grep -Fq 'if (state.fullRefreshRequested && state.session && !state.navigationPending)' "$JS"
grep -Fq 'scheduleDataRefresh(retryDelay, false, refreshReason || "trailing-full")' "$JS"
grep -Fq 'if (bootstrapLite) scheduleDataRefresh(0, true, "bootstrap-full")' "$JS"
grep -Fq 'state.navigationPending = true;' "$JS"
grep -Fq 'state.fullRefreshRequested = false;' "$JS"
grep -Fq 'var runtimeReady=w&&w.up===true&&w.disabled!==true' "$JS"
grep -Fq 'if(runtimeReady){' "$JS"
grep -Fq 'function stationRateDetail(sta, direction)' "$JS"
grep -Fq 'function stationPhyHtml(sta, compact)' "$JS"
grep -Fq 'function parseStationRateDetail(sta, direction)' "$JS"
grep -Fq 'function configuredPhyCeiling2x2(radio)' "$JS"
grep -Fq 'nssSource = "reported"' "$JS"
grep -Fq 'nssSource = "ht-mcs"' "$JS"
grep -Fq 'rateSource: hasRate ? "byte-counter-delta" : ""' "$JS"
grep -Fq 'tx_rate_detail:s.tx_rate_detail' "$JS"
grep -Fq 'rx_rate_detail:s.rx_rate_detail' "$JS"
grep -Fq 'آخر معدل PHY TX/RX — ليس سرعة نقل البيانات' "$JS"
grep -Fq 'Last PHY TX/RX rate — not throughput' "$JS"
grep -Fq 'Last instantaneous PHY rate reported by the AP; not traffic throughput.' "$JS"
grep -Fq 'Client is idle/asleep; a last PHY rate as low as 1 Mbps is normal during sleep' "$JS"
grep -Fq 'Byte-counter deltas only; last PHY snapshots and expected_mbps are never used as traffic.' "$JS"
grep -Fq '?lite=1&probe=1&live=1&speedping=' "$JS"
grep -Fq '?speedtest=1&nonce=' "$JS"
grep -Fq 'await payload.arrayBuffer()' "$JS"
grep -Fq 'async function measureLocalSpeed(onProgress)' "$JS"
grep -Fq 'var result = await measureLocalSpeed(setG)' "$JS"
grep -Fq 'ov.setAttribute("role", "dialog")' "$JS"
grep -Fq 'ov.setAttribute("aria-modal", "true")' "$JS"
grep -Fq 'if (e.key === "Escape")' "$JS"
grep -Fq 'بحث سريع في أقسام اللوحة' "$JS"
grep -Fq 'function applyNavSearchFilter(value)' "$JS"
grep -Fq 'function updateNavSearchCopy()' "$JS"
grep -Fq 'function resetNavSearchFilter()' "$JS"
grep -Fq 'resetNavSearchFilter();' "$JS"
grep -Fq 'var POLL_INTERVALS = [5, 15, 30, 60]' "$JS"
grep -Fq 'return POLL_INTERVALS.indexOf(interval) >= 0 ? interval : 5' "$JS"
grep -Fq 'var initialPollInterval = validPollInterval(5)' "$JS"
grep -Fq '<option value="5" selected>5s</option>' "$HTML"
grep -Fq 'var navShapeValid = navButtons.length === nav.length;' "$JS"
grep -Fq 'Keep the navigation button nodes stable across live-data, language, and' "$JS"
! grep -Fq 'fetchWithTimeout("dashboard.js?sp="' "$JS"
grep -Fq "*'&speedtest=1&'*" "$ROOT/files/www/cgi-bin/dashapi2"
grep -Fq 'Content-Length: 8388608' "$ROOT/files/www/cgi-bin/dashapi2"
grep -Fq 'dd if=/dev/zero bs=65536 count=128' "$ROOT/files/www/cgi-bin/dashapi2"
grep -Fq 'Diagnostic last-snapshot ordering only; no global ceiling comparison or throughput verdict.' "$JS"
! grep -Fq 'var MAX=1201' "$JS"
! grep -Fq 'Math.round(rate/b)' "$JS"
! grep -Fq 'if(r>=700)two++' "$JS"
! grep -Fq 'H.clamp(tx/ex*100' "$JS"
! grep -Fq 'inferred from radio htmode' "$JS"
! grep -Fq 'Closest to Ceiling' "$JS"
! grep -Fq 'Per-Client PHY Efficiency' "$JS"
! grep -Fq 'Spectral Efficiency' "$JS"
! grep -Fq 'Airtime Efficiency' "$JS"
grep -Fq 'ms / 60000, 1) + " min"' "$JS"
grep -Fq 'var retries = num(sta.tx_retries), failed = num(sta.tx_failed), inactive = num(sta.inactive_ms);' "$JS"
grep -Fq 'var linkCell = esc(d.iface || "") + stationPhyHtml(d, true);' "$JS"
grep -Fq 'var phyStr = stationPhyHtml(s, false);' "$JS"
! grep -Fq 'TX = AP→client (download)' "$JS"
grep -Fq 'var presets = [5, 10, 15, 20, 23, 26, 30, 35, 38]' "$JS"
grep -Fq 'value >= Number(range.min) && value <= Number(range.max)' "$JS"
grep -Fq 'type="range"' "$JS"
grep -Fq '<fieldset class="royal-field txpower-fieldset' "$JS"
grep -Fq 'aria-describedby="' "$JS"
grep -Fq 'class="txpower-presets" role="group" aria-label=' "$JS"
grep -Fq 'Configured' "$JS"
grep -Fq 'airtime use not measured' "$JS"
grep -Fq 'DL MU-MIMO (AX)' "$JS"
grep -Fq 'DL MU-MIMO (AC)' "$JS"
grep -Fq 'cap · unmeasured' "$JS"
! grep -Fq '["OFDMA","✓ fw"' "$JS"
grep -Fq '["DL OFDMA","cap · unmeasured"' "$JS"
grep -Fq 'var ulState=String(p.ul_muru_guard_state||p.ul_muru_state||"unknown")' "$JS"
grep -Fq 'p.ul_muru_guard_healthy===true' "$JS"
grep -Fq 'H.num(p.ul_muru_mask_module)' "$JS"
grep -Fq 'String(p.ul_muru_host_request||"unknown")' "$JS"
grep -Fq 'p.ul_muru_airtime_evidence||"unverified"' "$JS"
grep -Fq 'p.ul_muru_ota_evidence||"not-established"' "$JS"
grep -Fq 'ulRequest==="mask15-guarded"&&ulMask===15&&ulState==="armed"&&ulGuardHealthy' "$JS"
grep -Fq 'mask15 · guarded · airtime unverified' "$JS"
grep -Fq 'mask15 · guard stale/stopped · airtime unverified' "$JS"
grep -Fq 'it is not firmware-apply, airtime, OTA, or sale-readiness proof' "$JS"
! grep -Fq 'String(p.ul_muru_module)==="Y"' "$JS"
grep -Fq 'function markLiveSnapshotUnavailable()' "$JS"
grep -Fq 'liveDataUnavailable: false' "$JS"
grep -Fq 'function paintLiveUnavailableSection(id)' "$JS"
grep -Fq 'function isLiveDataSection(id)' "$JS"
grep -Fq 'overview|network|devices|wifi|insights|system|actions' "$JS"
grep -Fq 'else if (state.liveDataUnavailable)' "$JS"
grep -Fq 'state.liveDataUnavailable = true' "$JS"
grep -Fq 'window.__lastApi = null' "$JS"
grep -Fq 'window.addEventListener("pagehide"' "$JS"
grep -Fq 'window.addEventListener("pageshow"' "$JS"
grep -Fq 'window.location.reload();' "$JS"
grep -Fq 'chartDrawJobs = Object.create(null);' "$JS"
grep -Fq 'no previous snapshot is displayed' "$JS"
grep -Fq 'Live data unavailable' "$JS"
! grep -Fq 'localStorage' "$JS"
! grep -Fq 'sessionStorage' "$JS"
grep -Fq 'state.liveAvailability = state.liveAvailability.slice(-60)' "$JS"
grep -Fq 'Temporary memory for this open page only' "$JS"
grep -Fq 'ulRequest==="mask0-fault-disabled"?"mask0 · fault disabled"' "$JS"
grep -Fq 'ulRequest==="mask0-guard-unhealthy"?"mask0 · guard state missing/invalid"' "$JS"
grep -Fq '["UL OFDMA",ulLabel' "$JS"
grep -Fq '["UL MU-MIMO",ulLabel' "$JS"
grep -Fq '["Background CAC","driver · runtime probe"' "$JS"
grep -Fq 'The UL host request is reported from the MURU mask and guard separately.' "$JS"
grep -Fq 'not firmware-apply, airtime, OTA, or sale-readiness proof.' "$JS"
! grep -Fq 'only an explicit lab opt-in arms the real MCU fields' "$JS"
! grep -Fq 'real MCU fields are armed with a reset/hang guard' "$JS"
! grep -Fq '?p.txpower:38' "$JS"
! grep -Fq 'BSS color capable' "$JS"
! grep -Fq 'old clients never slow new ones' "$JS"
grep -Fq '/usr/sbin/cr6608-safe-wifi-reload 20 "$backup" "$radio"' "$ROOT/files/www/cgi-bin/dashaction"
grep -Fq 'if [ "$rc" != "0" ]; then' "$ROOT/files/www/cgi-bin/dashaction"
grep -Fq 'the previous Wi-Fi configuration and runtime were restored' "$ROOT/files/www/cgi-bin/dashaction"
! grep -Fq '/sbin/wifi reload' "$ROOT/files/www/cgi-bin/dashaction"

grep -Fq "if (Number.isFinite(applied))" \
	"$ROOT/files/www/luci-static/resources/view/cr6608/quicksettings.js"
! grep -Fq "' / Current=' + appliedText" \
	"$ROOT/files/www/luci-static/resources/view/cr6608/quicksettings.js"
grep -Fq 'dir="{{ dispatcher.lang == '\''ar'\'' ? '\''rtl'\'' : '\''ltr'\'' }}"' \
	"$ROOT/files/usr/share/ucode/luci/template/themes/argon/header.ut"
grep -Fq 'dir="{{ dispatcher.lang == '\''ar'\'' ? '\''rtl'\'' : '\''ltr'\'' }}"' \
	"$ROOT/files/usr/share/ucode/luci/template/themes/argon/header_login.ut"
grep -Fq '.insight-summary' "$CSS"
grep -Fq '.insight-tabs' "$CSS"
grep -Fq '.sr-only {' "$CSS"
grep -Fq '.txpower-fieldset {' "$CSS"
grep -Fq '@media (max-width:1180px)' "$CSS"
grep -Fq '@media (max-width:900px)' "$CSS"
grep -Fq '@media (max-width:820px)' "$CSS"
grep -Fq '@media (max-width:520px)' "$CSS"
grep -Fq '@media (max-width:380px)' "$CSS"
grep -Fq 'grid-template-columns:repeat(5,minmax(0,1fr))' "$CSS"
grep -Fq 'grid-template-rows:repeat(2,minmax(0,1fr))' "$CSS"
grep -Fq 'padding-block-end:calc(164px + env(safe-area-inset-bottom))' "$CSS"
! grep -Fq '.brand::after' "$CSS"
! grep -Fq 'CONTROL PLANE' "$CSS"
[ "$(grep -Fc ':root {' "$CSS")" -eq 1 ]
grep -Fq 'html[data-theme="light"] .btn' "$CSS"
grep -Fq 'html[data-theme="light"] .table-wrap' "$CSS"
grep -Fq 'html[data-theme="light"] .ctl-input' "$CSS"
grep -Fq 'html[dir="ltr"] .hero h2' "$CSS"
! grep -Eq '@media[[:space:]]*\(max-width:(430|560|1100)px\)' "$CSS"
grep -Fq 'class="sr-only gauge-summary"' "$JS"
grep -Fq 'class="spark" viewBox="0 0 120 24" aria-hidden="true" focusable="false"' "$JS"
[ "$(grep -Fc '<table' "$JS")" -eq 7 ]
[ "$(grep -Fc 'tableCaption(' "$JS")" -eq 8 ]
! grep -Fq '<th>' "$JS"
grep -Fq '<th scope="col">' "$JS"
grep -Fq "<th scope='row'" "$JS"
grep -Fq '.insight-tabs { inline-size:100%; max-inline-size:100%; display:grid; grid-template-columns:repeat(2,minmax(0,1fr))' "$CSS"
grep -Fq '.isolation-apply { position:static' "$CSS"
grep -Fq '.main { padding-block-end:calc(160px + env(safe-area-inset-bottom))' "$CSS"
grep -Fq '.side { block-size:132px; min-block-size:0; overflow:visible; }' "$CSS"
grep -Fq -- '-webkit-line-clamp:2' "$CSS"
grep -Fq "option rollback '90'" "$LUCI"
grep -Fq "ucode_prefix '/cgi-bin/luci=/usr/share/ucode/luci/uhttpd.uc'" "$UHTTPD"
! grep -Fq 'lua_prefix' "$UHTTPD"
grep -Fq "http.redirect('/');" "$LUCI_SYSAUTH"
grep -Fq 'LUCI_MAPPING="/cgi-bin/luci=$LUCI_HANDLER"' "$SMARTAP_ONLY_MIGRATION"
grep -Fq 'id="openWrtBtn"' "$HTML"
grep -Fq 'async function ensureLuciSession()' "$JS"
grep -Fq '/cgi-bin/dashluci' "$JS"
grep -Fq 'window.location.assign("/cgi-bin/luci/admin/network/wireless")' "$JS"
grep -Fq 'function quiesceDataReadsForNavigation()' "$JS"
grep -Fq 'if (!state.session || state.navigationPending) return false;' "$JS"
grep -Fq 'await quiesceDataReadsForNavigation();' "$JS"
grep -Fq 'class="traffic-layout"' "$JS"
grep -Fq 'class="latency-metrics"' "$JS"
grep -Fq 'هذا زمن استجابة واجهة الراوتر، وليس Ping للإنترنت.' "$JS"
grep -Fq '.traffic-layout {' "$CSS"
grep -Fq '.traffic-table table { min-inline-size:780px; }' "$CSS"
grep -Fq '/^(?:wan|lan[1-3])$/' "$JS"
grep -Fq '"DSA errors"' "$JS"
grep -Fq '"DSA drops"' "$JS"
grep -Fq '"Errors / Drops since interface reset"' "$JS"
grep -Fq 'function renderLinkDiagnostics(data)' "$JS"
grep -Fq 'port.connected === true && Number(port.speed_mbps) === 100 && Number(port.capability_mbps) === 1000' "$JS"
grep -Fq 'is linked at 100 Mbps although this CR6608 DSA port supports 1000 Mbps.' "$JS"
grep -Fq 'Use an 8-wire Cat5e/Cat6 cable, reseat both ends, or try another router/switch port.' "$JS"
grep -Fq 'Fallback count covers only the currently available log buffer from this boot; older events may have rolled out.' "$JS"
grep -Fq 'renderLinkDiagnostics(data) + interfaceCard' "$JS"
grep -Fq 'function verifiedUplinkCapacity(data)' "$JS"
grep -Fq 'traffic.topology_complete !== true' "$JS"
grep -Fq 'canvas.dataset.chartStable = "1"' "$JS"
grep -Fq 'canvas === $(canvasId)' "$JS"
grep -Fq 'Raw interface-counter directions; these are not client download/upload.' "$JS"
grep -Fq 'Each interface is independent; bars are relative only to the busiest interface.' "$JS"
grep -Fq 'Bridge/port/AP layers may overlap, so no grand total is shown.' "$JS"
grep -Fq 'Runtime Counter Snapshot' "$JS"
grep -Fq 'System Resource Score' "$JS"
grep -Fq 'No resource warnings in available score inputs' "$JS"
grep -Fq 'Observed Resource Headroom' "$JS"
grep -Fq 'No CPU, RAM, or airtime inputs' "$JS"
grep -Fq 'CPU/RAM/airtime snapshot; not network capacity or a load test.' "$JS"
grep -Fq 'Strong-signal 2.4G Clients' "$JS"
grep -Fq '5G client capability and a steering decision are not verified.' "$JS"
! grep -Fq 'No sticky clients — good distribution' "$JS"
! grep -Fq "A?'آمن':'clear'" "$JS"
grep -Fq 'esc(title)' "$JS"
grep -Fq 'esc(chip)' "$JS"
grep -Fq 'esc(desc)' "$JS"
! grep -Fq 'CAP=1000000000' "$JS"
! grep -Fq 'Weekly Digest' "$JS"
! grep -Fq 'Network Score' "$JS"
! grep -Fq 'ALL GOOD' "$JS"
! grep -Fq 'ALL OK' "$JS"
! grep -Fq 'No tips — all tuned' "$JS"
! grep -Fq 'never dropped' "$JS"
! grep -Fq 'Co-Channel Pressure' "$JS"
! grep -Fq 'Management Exposure' "$JS"
! grep -Fq 'Rogue Neighbor Watch' "$JS"
! grep -Fq 'WPA / PMF Posture' "$JS"
! grep -Fq 'Gateway RTT Grade' "$JS"
! grep -Fq 'Jitter Estimate' "$JS"
! grep -Fq 'var ifaceFaults =' "$JS"
! grep -Fq 'background:var(--panel)' "$HTML"
grep -Fq 'id="loginLangAr"' "$HTML"
grep -Fq 'b.setAttribute("aria-current", "page")' "$JS"
grep -Fq 'data._liveLite === true && /^(devices|wifi)$/' "$JS"
grep -Fq 'state.interval = validPollInterval(state.interval)' "$JS"
grep -Fq 'role="tabpanel"' "$JS"
grep -Fq 'aria-selected="true"' "$JS"
grep -Fq 'maximum-scale=5.0' "$ROOT/files/usr/share/ucode/luci/template/themes/argon/header.ut"
! grep -Fq 'user-scalable=no' "$ROOT/files/usr/share/ucode/luci/template/themes/argon/header.ut"
grep -Fq 'aria-controls="mainmenu"' "$ROOT/files/usr/share/ucode/luci/template/themes/argon/header.ut"
grep -Fq 'self.loadMenu(attempt + 1)' "$MENU_ARGON"
grep -Fq "var expandHandler = l == 1 && hasChildren ? ui.createHandlerFn(this, 'handleMenuExpand') : null;" "$MENU_ARGON"
! grep -Fq "'click': l == 1 ? ui.createHandlerFn(this, 'handleMenuExpand') : null" "$MENU_ARGON"
grep -Fq "element.getAttribute('data-cr6608-sidebar-bound') == '1'" "$MENU_ARGON"
grep -Fq "showSide.setAttribute('aria-controls', 'mainmenu')" "$MENU_ARGON"
grep -Fq "showSide.setAttribute('aria-expanded'" "$MENU_ARGON"
sidebar_bind_calls="$(grep -Fc 'this.bindSidebarControls();' "$MENU_ARGON")"
[ "$sidebar_bind_calls" -ge 2 ]
node --check "$MENU_ARGON_RUNTIME"
node "$MENU_ARGON_RUNTIME"
node "$ROOT/tests/test-lan-scan-render.js" "$JS"

# Only the Argon menu adapter and the CR6608 view may override LuCI resources.
resource_count="$(find "$RESOURCES" -type f | wc -l | tr -d ' ')"
[ "$resource_count" = 2 ]
[ -f "$RESOURCES/menu-argon.js" ]
[ -f "$RESOURCES/view/cr6608/quicksettings.js" ]
[ ! -e "$RESOURCES/luci.js" ]
[ ! -e "$ROOT/files/sbin/sysupgrade" ]
[ ! -e "$ROOT/files/lib/netifd/wireless/mac80211.sh" ]
[ ! -e "$ROOT/files/usr/lib/lua/luci/version.lua" ]
grep -Fq "revision = '26.181.75678~128a781-smartap-v86'" "$LUCI_VERSION"

# The release gate must execute the pinned browser test. Generated screenshots
# are evidence artifacts, not source inputs, and are published separately.
grep -Fq 'node --check "${MOBILE_LAYOUT_TEST}"' "$BUILD"
grep -Fq 'mobile_layout_output="$(node "${MOBILE_LAYOUT_TEST}")"' "$BUILD"
grep -Fq 'mobile_layout_tests=pass' "$BUILD"
grep -Fq 'for design_width in 360 390 430 1440; do' "$BUILD"
grep -Fq 'smartap-design-${design_language}-${design_theme}-${design_width}.png' "$BUILD"
grep -Fq 'Required design-system screenshot is missing or unsafe' "$BUILD"
grep -Fq 'ui-browser-screenshots.tar.xz' "$BUILD"
grep -Fq 'exec "${SCRIPT_DIR}/build.sh"' "$PUBLISH"
! grep -Fq 'LAB38' "$PUBLISH"
! grep -Fq 'current-lab38' "$PUBLISH"

# Every file under files/ is copied into the OpenWrt overlay, recorded in the
# source manifest, and compared byte-for-byte with the extracted image rootfs.
grep -Fq 'cp -a "${SRC_FILES}/." "${OPENWRT_DIR}/files/"' "$BUILD"
grep -Fq 'done < <(find "${SRC_FILES}" -mindepth 1 -print0 | LC_ALL=C sort -z)' "$BUILD"
grep -Fq 'find "${STAGED_OVERLAY}" -mindepth 1 -print0 > "${overlay_list}"' "$INSPECTOR"
grep -Fq 'overlay file missing from rootfs: ${relative_path}' "$INSPECTOR"

# Failed control replies must refresh live state but never enter the success
# event stream.  Preserve this ordering for generic actions and the two
# per-client controls that previously reported success for {ok:false}.
action_block="$(sed -n '/^  async function action(name, button)/,/^  function activeControlSection/p' "$JS")"
action_guard_line="$(printf '%s\n' "$action_block" | grep -nF 'if (!j || j.ok !== true)' | head -n1 | cut -d: -f1)"
action_event_line="$(printf '%s\n' "$action_block" | grep -nF 'event(name +' | head -n1 | cut -d: -f1)"
[ -n "$action_guard_line" ] && [ -n "$action_event_line" ] && [ "$action_guard_line" -lt "$action_event_line" ]
printf '%s\n' "$action_block" | grep -A8 -F 'if (!j || j.ok !== true)' | grep -Fq 'return;'

limit_block="$(sed -n '/if (act === "__limit")/,/await runDeviceAccessAction/p' "$JS")"
limit_guard_line="$(printf '%s\n' "$limit_block" | grep -nF 'if (!jl || jl.ok !== true)' | head -n1 | cut -d: -f1)"
limit_event_line="$(printf '%s\n' "$limit_block" | grep -nF 'event("Limit "' | head -n1 | cut -d: -f1)"
[ -n "$limit_guard_line" ] && [ -n "$limit_event_line" ] && [ "$limit_guard_line" -lt "$limit_event_line" ]
printf '%s\n' "$limit_block" | grep -A6 -F 'if (!jl || jl.ok !== true)' | grep -Fq 'return;'

steer_block="$(sed -n '/querySelectorAll("\[data-steer-mac\]")/,/^  function startPolling/p' "$JS")"
steer_guard_line="$(printf '%s\n' "$steer_block" | grep -nF 'if (!j || j.ok !== true)' | head -n1 | cut -d: -f1)"
steer_event_line="$(printf '%s\n' "$steer_block" | grep -nF 'event("Steer 5G:' | head -n1 | cut -d: -f1)"
[ -n "$steer_guard_line" ] && [ -n "$steer_event_line" ] && [ "$steer_guard_line" -lt "$steer_event_line" ]
printf '%s\n' "$steer_block" | grep -A6 -F 'if (!j || j.ok !== true)' | grep -Fq 'return;'

# UI reliability contracts: LuCI handoff must abort replaceable polling instead
# of waiting for the full API timeout, and all user-triggered diagnostics must
# release their buttons on every terminal path.
navigation_block="$(sed -n '/^  function quiesceDataReadsForNavigation()/,/^  async function resumeStartupSession/p' "$JS")"
printf '%s\n' "$navigation_block" | grep -Fq 'cancelDataRead();'
printf '%s\n' "$navigation_block" | grep -Fq 'var deadline = Date.now() + 1500;'
! printf '%s\n' "$navigation_block" | grep -Fq 'API_TIMEOUT_MS'
! printf '%s\n' "$navigation_block" | grep -Fq 'state.navigationPending = false'

selftest_block="$(sed -n '/var stBtn = dynamicId(root, "selftestBtn")/,/querySelectorAll("\[data-steer-mac\]")/p' "$JS")"
printf '%s\n' "$selftest_block" | grep -Fq '} finally {'
printf '%s\n' "$selftest_block" | grep -Fq 'stBtn.disabled = false;'
printf '%s\n' "$selftest_block" | grep -Fq 'stBtn.textContent = old;'

grep -Fq 'if (state.speedTestBusy) return false;' "$JS"
grep -Fq 'if (!beginSpeedTest(button)) return;' "$JS"
grep -Fq 'finishSpeedTest(button);' "$JS"
grep -Fq 'if (name === "speedtest") return speedTest(button);' "$JS"

grep -Fq 'this.loadMenuWithTimeout(5000)' "$MENU_ARGON"
grep -Fq "reject(new Error('menu-load-timeout'))" "$MENU_ARGON"
grep -Fq 'window.clearTimeout(timer);' "$MENU_ARGON"
grep -Fq 'self.renderLoadFailure(error);' "$MENU_ARGON"

grep -Fq 'min-block-size:100dvh' "$CSS"
grep -Fq 'overflow-y:auto' "$CSS"
grep -Fq '.seg button { min-block-size:44px' "$CSS"
grep -Fq '.controls>*,.controls .btn,.controls select { inline-size:100%; min-inline-size:0; min-block-size:44px' "$CSS"
grep -Fq 'maximum-scale=5.0' "$ROOT/files/usr/share/ucode/luci/template/themes/argon/header_login.ut"
! grep -Fq 'user-scalable=no' "$ROOT/files/usr/share/ucode/luci/template/themes/argon/header_login.ut"

printf 'dashboard_ui_contracts=pass\n'
