#!/bin/sh /etc/rc.common

START=96
STOP=10

start() {
	(
		sleep 8
		/usr/sbin/cr6608-dhcp-guard br-lan
	) &
}

reload_service() {
	/usr/sbin/cr6608-dhcp-guard br-lan
}

restart() {
	reload_service
}
