#!/bin/sh /etc/rc.common
# The one background caretaker (LED / Wi-Fi presence / rescue IPs / txpower pin).
START=98
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/cr6608-guardian
	procd_set_param respawn 3600 5 0
	procd_close_instance
}
