#!/bin/sh

# root password = admin
ROOT_HASH='$1$3DsbAr5N$AGVUSi6u70o59j.sixtMP.'
sed -i "s|^root:[^:]*:|root:${ROOT_HASH}:|" /etc/shadow

uci set system.@system[0].zonename='Asia/Aden'
uci set system.@system[0].timezone='<+03>-3'
uci commit system

uci set network.lan=interface
uci set network.lan.device='br-lan'
uci set network.lan.proto='static'
uci set network.lan.ipaddr='192.168.1.1'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.delegate='0'
uci delete network.lan.ip6assign 2>/dev/null
uci delete network.globals.ula_prefix 2>/dev/null
uci delete network.wan6 2>/dev/null
uci commit network

uci set dhcp.lan=dhcp
uci set dhcp.lan.interface='lan'
uci set dhcp.lan.ignore='1'
uci set dhcp.lan.dhcpv4='disabled'
uci set dhcp.lan.dhcpv6='disabled'
uci set dhcp.lan.ra='disabled'
uci set dhcp.lan.ndp='disabled'
uci set dhcp.odhcpd.maindhcp='0'
uci commit dhcp

/etc/init.d/dnsmasq disable 2>/dev/null
/etc/init.d/dnsmasq stop 2>/dev/null
/etc/init.d/odhcpd disable 2>/dev/null
/etc/init.d/odhcpd stop 2>/dev/null

[ -s /etc/config/wireless ] || wifi config

# احذف كل واجهات الواي فاي القديمة حتى لا يدمج 2.4 و 5 بنفس الاسم
while uci -q delete wireless.@wifi-iface[0]; do :; done

RAD24=""
RAD5=""
for r in $(uci show wireless | sed -n "s/^wireless\.\([^=]*\)=wifi-device.*/\1/p"); do
	b="$(uci -q get wireless.$r.band)"
	[ "$b" = "2g" ] && RAD24="$r"
	[ "$b" = "5g" ] && RAD5="$r"
done
[ -n "$RAD24" ] || RAD24="radio0"
[ -n "$RAD5" ] || RAD5="radio1"

uci set wireless.$RAD24.disabled='0'
uci set wireless.$RAD24.country='US'
uci set wireless.$RAD24.channel='11'
uci set wireless.$RAD24.htmode='HE20'
uci set wireless.$RAD24.txpower='38'

uci set wireless.wifinet0=wifi-iface
uci set wireless.wifinet0.device="$RAD24"
uci set wireless.wifinet0.mode='ap'
uci set wireless.wifinet0.network='lan'
uci set wireless.wifinet0.ssid='Smart ap 2.4G'
uci set wireless.wifinet0.encryption='none'
uci set wireless.wifinet0.hidden='0'
uci set wireless.wifinet0.disabled='0'
uci set wireless.wifinet0.disassoc_low_ack='0'
uci set wireless.wifinet0.max_inactivity='3600'

uci set wireless.$RAD5.disabled='0'
uci set wireless.$RAD5.country='US'
uci set wireless.$RAD5.channel='36'
uci set wireless.$RAD5.htmode='HE80'
uci set wireless.$RAD5.txpower='38'

uci set wireless.wifinet1=wifi-iface
uci set wireless.wifinet1.device="$RAD5"
uci set wireless.wifinet1.mode='ap'
uci set wireless.wifinet1.network='lan'
uci set wireless.wifinet1.ssid='Smart ap 5G'
uci set wireless.wifinet1.encryption='none'
uci set wireless.wifinet1.hidden='0'
uci set wireless.wifinet1.disabled='0'
uci set wireless.wifinet1.disassoc_low_ack='0'
uci set wireless.wifinet1.max_inactivity='3600'

uci commit wireless

/etc/init.d/uhttpd enable 2>/dev/null
/etc/init.d/uhttpd restart 2>/dev/null

wifi reload 2>/dev/null || wifi up 2>/dev/null
exit 0
