#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/cr6608-dashboard-prewarm
	procd_set_param nice 10
	procd_set_param stdout 0
	procd_set_param stderr 0
	procd_close_instance
}
