#!/bin/sh /etc/rc.common
# Internet LED follows real cable state on ANY wired port (see cr6608-led-watch).
START=98
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/cr6608-led-watch
	procd_set_param respawn 3600 5 0
	procd_close_instance
}
