package com.binwaps.cardmanager.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Bolt
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.binwaps.cardmanager.data.Store
import com.binwaps.cardmanager.mikrotik.MikrotikClient
import com.binwaps.cardmanager.model.CardMode
import com.binwaps.cardmanager.model.UploadTarget
import com.binwaps.cardmanager.model.UserEntry
import com.binwaps.cardmanager.print.PdfExporter
import com.binwaps.cardmanager.print.PrintEngine
import com.binwaps.cardmanager.ui.components.AppField
import com.binwaps.cardmanager.ui.components.CardPreview
import com.binwaps.cardmanager.ui.components.GhostButton
import com.binwaps.cardmanager.ui.components.NeonButton
import com.binwaps.cardmanager.ui.components.NeonProgress
import com.binwaps.cardmanager.ui.components.SectionHeader
import com.binwaps.cardmanager.ui.theme.Danger
import com.binwaps.cardmanager.ui.theme.GlassCard
import com.binwaps.cardmanager.ui.theme.Lime
import com.binwaps.cardmanager.ui.theme.Neon
import com.binwaps.cardmanager.ui.theme.Panel
import com.binwaps.cardmanager.ui.theme.ScreenGradient
import com.binwaps.cardmanager.ui.theme.Stroke
import com.binwaps.cardmanager.ui.theme.TextHi
import com.binwaps.cardmanager.ui.theme.TextLow
import com.binwaps.cardmanager.ui.theme.TextMid
import com.binwaps.cardmanager.util.Charset
import com.binwaps.cardmanager.util.UserGenerator
import com.binwaps.cardmanager.util.toCountOrNull
import kotlinx.coroutines.launch

/** حالة الرفع للراوتر داخل الشاشة السريعة */
private sealed interface UploadState {
    data object Idle : UploadState
    data class Running(val done: Int, val total: Int) : UploadState
    data class Done(val ok: Int, val total: Int) : UploadState
    data class Failed(val error: String, val remaining: List<UserEntry>) : UploadState
    data object Skipped : UploadState
}

/**
 * الطباعة السريعة — أسلوب سمارت كريتور بالضبط:
 * اختر القالب والباقة واضبط العدد، وزر واحد يولّد الكروت،
 * يرفعها للميكروتك (متدفقاً وبسرعة)، ويبني PDF واحداً — معاً وبالتوازي.
 */
@Composable
fun ExpressScreen() {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val templates by Store.templates.collectAsState()
    val profiles by Store.profiles.collectAsState()
    val settings by Store.settings.collectAsState()
    val routers by Store.routers.collectAsState()
    val engineState by PrintEngine.state.collectAsState()
    LaunchedEffect(Unit) { PrintEngine.restoreIfAny() }

    var templateId by remember { mutableStateOf(Store.defaultTemplateOrFirst()?.id) }
    val template = templates.firstOrNull { it.id == templateId } ?: Store.defaultTemplateOrFirst()

    var count by remember { mutableStateOf("100") }
    var length by remember { mutableStateOf("6") }
    var mode by remember { mutableStateOf(settings.cardMode) }
    var profile by remember { mutableStateOf(profiles.firstOrNull()?.name ?: "") }
    var price by remember { mutableStateOf(profiles.firstOrNull()?.price ?: "") }
    var validity by remember { mutableStateOf("") }
    var target by remember { mutableStateOf(settings.uploadTarget) }
    var uploadEnabled by remember { mutableStateOf(routers.isNotEmpty()) }

    var upload by remember { mutableStateOf<UploadState>(UploadState.Idle) }
    var generated by remember { mutableStateOf<List<UserEntry>>(emptyList()) }

    val engineBusy = engineState is PrintEngine.State.Running
    val uploadBusy = upload is UploadState.Running
    val busy = engineBusy || uploadBusy

    fun doUpload(cards: List<UserEntry>) {
        if (cards.isEmpty()) return
        upload = UploadState.Running(0, cards.size)
        scope.launch {
            val created = java.util.Collections.synchronizedList(mutableListOf<UserEntry>())
            val result = when (target) {
                UploadTarget.HOTSPOT -> MikrotikClient.createHotspotUsers(
                    Store.activeRouter(), cards,
                    onProgress = { d, t -> upload = UploadState.Running(d, t) },
                    onCreated = { created.add(it) },
                )
                UploadTarget.USER_MANAGER -> MikrotikClient.createUserManagerUsers(
                    Store.activeRouter(), cards,
                    onProgress = { d, t -> upload = UploadState.Running(d, t) },
                    onCreated = { created.add(it) },
                )
            }
            Store.markUploaded(created.map { it.username })
            upload = result.fold(
                onSuccess = { ok ->
                    if (ok >= cards.size) UploadState.Done(ok, cards.size)
                    else UploadState.Failed(
                        "رُفع $ok من ${cards.size}",
                        cards.filterNot { c -> created.any { it.username == c.username } },
                    )
                },
                onFailure = {
                    UploadState.Failed(
                        it.message ?: "فشل الرفع",
                        cards.filterNot { c -> created.any { it.username == c.username } },
                    )
                },
            )
        }
    }

    fun go() {
        val t0 = template ?: return
        val n = (count.toCountOrNull() ?: 0).coerceIn(1, 100000)
        // نطاق الطباعة والنسخ لا يتدخلان في الوضع السريع — الكل يُطبع مرة واحدة
        val quickSettings = settings.copy(
            cardMode = mode, printFrom = 0, printTo = 0, startCell = 1, copies = 1,
        )
        Store.updateSettings(quickSettings.copy(uploadTarget = target))

        val cards = UserGenerator.generate(
            count = n,
            prefix = "",
            length = (length.toCountOrNull() ?: 6).coerceIn(3, 20),
            charset = Charset.DIGITS,
            mode = mode,
            passwordLength = 4,
            profile = profile,
            price = price,
            validity = validity,
            serialStart = 1,
            batchTag = "vc-" + java.text.SimpleDateFormat("yyMMdd-HHmm", java.util.Locale.US)
                .format(java.util.Date()),
        )
        generated = cards
        Store.addUsers(cards)

        // الرفع والطباعة ينطلقان معاً — لا انتظار أحدهما للآخر
        if (uploadEnabled && routers.isNotEmpty()) doUpload(cards) else upload = UploadState.Skipped
        PrintEngine.startPdf(context, t0, cards, quickSettings)
    }

    Column(
        Modifier
            .fillMaxSize()
            .background(ScreenGradient)
            .verticalScroll(rememberScrollState())
            .padding(16.dp),
    ) {
        SectionHeader("توليد وطباعة بخطوة واحدة", "قالب + عدد + باقة ← PDF ورفع فوري", Icons.Filled.Bolt)
        Spacer(Modifier.height(12.dp))

        // القالب
        Text("القالب", fontSize = 12.sp, color = TextLow)
        Spacer(Modifier.height(6.dp))
        Row(Modifier.horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(6.dp)) {
            templates.forEach { t ->
                Chip(t.name, t.id == template?.id) { templateId = t.id }
            }
        }
        Spacer(Modifier.height(9.dp))
        template?.let {
            GlassCard(Modifier.fillMaxWidth(), padding = 8) {
                CardPreview(template = it, modifier = Modifier.fillMaxWidth())
            }
        }

        Spacer(Modifier.height(12.dp))
        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            AppField(count, { count = it.filter { c -> c.isDigit() } }, "عدد الكروت", Modifier.weight(1f), numeric = true)
            AppField(length, { length = it.filter { c -> c.isDigit() } }, "عدد الأرقام", Modifier.weight(1f), numeric = true)
        }
        Spacer(Modifier.height(8.dp))
        Text("نوع الكرت", fontSize = 12.sp, color = TextLow)
        Spacer(Modifier.height(6.dp))
        Row(Modifier.horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(6.dp)) {
            CardMode.entries.forEach { m -> Chip(m.labelAr, mode == m) { mode = m } }
        }

        Spacer(Modifier.height(10.dp))
        Text("الباقة", fontSize = 12.sp, color = TextLow)
        Spacer(Modifier.height(6.dp))
        if (profiles.isNotEmpty()) {
            Row(Modifier.horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                profiles.forEach { p ->
                    Chip(p.name, profile == p.name) {
                        profile = p.name
                        if (p.price.isNotBlank()) price = p.price
                        if (p.sessionTimeout.isNotBlank()) validity = p.sessionTimeout
                    }
                }
            }
            Spacer(Modifier.height(7.dp))
        } else {
            var loadingProfiles by remember { mutableStateOf(false) }
            var profilesError by remember { mutableStateOf<String?>(null) }
            GhostButton(
                if (loadingProfiles) "جاري جلب الباقات…" else "جلب باقات الراوتر للاختيار منها",
                Modifier.fillMaxWidth(),
                enabled = !loadingProfiles,
            ) {
                loadingProfiles = true; profilesError = null
                scope.launch {
                    MikrotikClient.fetchProfiles(Store.activeRouter(), foreground = true)
                        .onSuccess { list ->
                            Store.setProfiles(list)
                            list.firstOrNull()?.let { p ->
                                if (profile.isBlank()) { profile = p.name; price = p.price }
                            }
                        }
                        .onFailure { profilesError = it.message ?: "فشل جلب الباقات" }
                    loadingProfiles = false
                }
            }
            profilesError?.let {
                Spacer(Modifier.height(5.dp))
                Text(it, fontSize = 10.5.sp, color = com.binwaps.cardmanager.ui.theme.Danger)
            }
            Spacer(Modifier.height(7.dp))
        }
        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            AppField(profile, { profile = it }, "اسم الباقة", Modifier.weight(1.2f))
            AppField(price, { price = it }, "السعر", Modifier.weight(0.9f), numeric = true)
            AppField(validity, { validity = it }, "الصلاحية", Modifier.weight(0.9f))
        }

        Spacer(Modifier.height(10.dp))
        Row(verticalAlignment = Alignment.CenterVertically) {
            Text("الرفع للراوتر", fontSize = 12.5.sp, color = TextMid, modifier = Modifier.weight(1f))
            Chip(if (uploadEnabled) "مفعّل ✓" else "بدون رفع", uploadEnabled) { uploadEnabled = !uploadEnabled }
            Spacer(Modifier.width(6.dp))
            UploadTarget.entries.forEach { tg ->
                Chip(tg.labelAr, target == tg) { target = tg }
                Spacer(Modifier.width(4.dp))
            }
        }
        if (routers.isEmpty()) {
            Text("لا يوجد راوتر محفوظ — سيُنشأ PDF فقط", fontSize = 10.5.sp, color = TextLow)
        }

        Spacer(Modifier.height(14.dp))
        NeonButton(
            "ولّد • ارفع • اطبع",
            Modifier.fillMaxWidth(),
            Icons.Filled.Bolt,
            enabled = !busy && template != null && (count.toCountOrNull() ?: 0) > 0,
        ) { go() }
        Spacer(Modifier.height(5.dp))
        Text(
            "الرفع للميكروتك وبناء الـ PDF يعملان معاً بالتوازي — متدفق وسريع حتى عن بُعد. " +
                "ملف PDF واحد لكل الكروت مهما كان العدد.",
            fontSize = 10.sp, color = TextLow,
        )

        // حالة الرفع
        when (val u = upload) {
            is UploadState.Running -> {
                Spacer(Modifier.height(10.dp))
                GlassCard(Modifier.fillMaxWidth(), glow = Neon.copy(alpha = 0.4f), padding = 11) {
                    Text("جاري الرفع للراوتر: ${u.done} من ${u.total}", fontSize = 12.sp, color = TextHi)
                    Spacer(Modifier.height(6.dp))
                    NeonProgress(u.done.toFloat() / u.total.coerceAtLeast(1))
                }
            }
            is UploadState.Done -> {
                Spacer(Modifier.height(10.dp))
                GlassCard(Modifier.fillMaxWidth(), glow = Lime.copy(alpha = 0.45f), padding = 11) {
                    Text("✓ رُفع ${u.ok} كرت للراوتر بنجاح", fontSize = 12.5.sp, color = Lime, fontWeight = FontWeight.Bold)
                }
            }
            is UploadState.Failed -> {
                Spacer(Modifier.height(10.dp))
                GlassCard(Modifier.fillMaxWidth(), glow = Danger.copy(alpha = 0.5f), padding = 11) {
                    Text("الرفع لم يكتمل: ${u.error}", fontSize = 12.sp, color = TextHi)
                    Spacer(Modifier.height(8.dp))
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        NeonButton("إعادة رفع الناقص (${u.remaining.size})") { doUpload(u.remaining) }
                        GhostButton("تجاهل") { upload = UploadState.Idle }
                    }
                }
            }
            else -> {}
        }

        // حالة الطباعة
        when (val es = engineState) {
            is PrintEngine.State.Running -> {
                Spacer(Modifier.height(10.dp))
                GlassCard(Modifier.fillMaxWidth(), glow = Neon.copy(alpha = 0.4f), padding = 11) {
                    Text(es.label, fontSize = 12.sp, color = TextHi)
                    Spacer(Modifier.height(6.dp))
                    NeonProgress(es.done.toFloat() / es.total.coerceAtLeast(1))
                }
            }
            is PrintEngine.State.Done -> {
                Spacer(Modifier.height(10.dp))
                GlassCard(Modifier.fillMaxWidth(), glow = Lime.copy(alpha = 0.5f), padding = 12) {
                    Text("✓ ملف PDF جاهز — ${es.total} كرت", fontSize = 13.sp, color = Lime, fontWeight = FontWeight.Bold)
                    Spacer(Modifier.height(9.dp))
                    Row(Modifier.horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        NeonButton("مشاركة الملف") { PdfExporter.shareAll(context, es.files) }
                        GhostButton("طباعة عبر النظام") { es.files.forEach { PdfExporter.printViaSystem(context, it) } }
                        GhostButton("تم") { PrintEngine.acknowledge() }
                    }
                }
            }
            is PrintEngine.State.Failed -> {
                Spacer(Modifier.height(10.dp))
                GlassCard(Modifier.fillMaxWidth(), glow = Danger.copy(alpha = 0.5f), padding = 11) {
                    Text(es.error, fontSize = 12.sp, color = TextHi)
                    Spacer(Modifier.height(8.dp))
                    NeonButton("استئناف") { PrintEngine.resume(context) }
                }
            }
            else -> {}
        }

        if (generated.isNotEmpty()) {
            Spacer(Modifier.height(10.dp))
            Text(
                "آخر دفعة: ${generated.size} كرت — تجدها في قسم الكروت وسجل الدفعات",
                fontSize = 11.sp, color = TextLow,
            )
        }
        Spacer(Modifier.height(30.dp))
    }
}

@Composable
private fun Chip(label: String, on: Boolean, onClick: () -> Unit) {
    Text(
        label,
        fontSize = 11.5.sp,
        color = if (on) Neon else TextMid,
        fontWeight = if (on) FontWeight.Bold else FontWeight.Normal,
        modifier = Modifier
            .background(if (on) Neon.copy(alpha = 0.12f) else Panel, RoundedCornerShape(999.dp))
            .border(1.dp, if (on) Neon.copy(alpha = 0.5f) else Stroke, RoundedCornerShape(999.dp))
            .clickable(onClick = onClick)
            .padding(horizontal = 11.dp, vertical = 6.dp),
    )
}
