#!/bin/sh

IFACE="${1:-br-lan}"
LOGTAG="cr6608-dhcp-guard"
PROBE_LOG="/tmp/cr6608-dhcp-guard.log"

log() {
	logger -t "$LOGTAG" "$*"
}

probe_upstream_dhcp() {
	[ -x /sbin/udhcpc ] || return 1
	rm -f "$PROBE_LOG"
	/sbin/udhcpc -n -q -t 2 -T 2 -i "$IFACE" -s /bin/true >"$PROBE_LOG" 2>&1
}

set_local_dhcp() {
	local enable="$1"

	if [ "$enable" = "1" ]; then
		uci set dhcp.lan.ignore='0'
		uci set cr6608quick.default.dhcp_server='1'
		log "no upstream DHCP detected on $IFACE; local DHCP enabled"
	else
		uci set dhcp.lan.ignore='1'
		uci set cr6608quick.default.dhcp_server='0'
		log "upstream DHCP detected on $IFACE; local DHCP disabled"
	fi

	uci commit dhcp
	uci commit cr6608quick
	/etc/init.d/dnsmasq restart >/dev/null 2>&1 || true
}

case "$2" in
	force-on)
		set_local_dhcp 1
		;;
	force-off)
		set_local_dhcp 0
		;;
	*)
		if probe_upstream_dhcp; then
			set_local_dhcp 0
		else
			set_local_dhcp 1
		fi
		;;
esac

exit 0
